/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-body)', 'Inter', '-apple-system', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'monospace'],
        display: ['var(--font-body)', 'Inter', 'sans-serif'],
      },
      colors: {
        brand: {
          50:  'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
        },
        surface: {
          page:      'var(--surface-page)',
          secondary: 'var(--surface-secondary)',
          subtle:    'var(--surface-subtle)',
          inset:     'var(--surface-inset)',
          elevated:  'var(--surface-elevated)',
          overlay:   'var(--surface-overlay)',
          // legacy backwards-compat
          '000': 'var(--surface-page)',
          '100': 'var(--surface-page)',
          '200': 'var(--surface-secondary)',
          '300': 'var(--surface-subtle)',
          '400': 'var(--surface-inset)',
          '500': 'var(--border-default)',
          '600': 'var(--border-strong)',
          '700': 'var(--text-tertiary)',
        },
        text: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary:  'var(--text-tertiary)',
          disabled:  'var(--text-disabled)',
          inverse:   'var(--text-inverse)',
          brand:     'var(--text-brand)',
          link:      'var(--text-link)',
        },
        border: {
          subtle:  'var(--border-subtle)',
          default: 'var(--border-default)',
          strong:  'var(--border-strong)',
          brand:   'var(--border-brand)',
          focus:   'var(--border-focus)',
          // legacy
          100: 'var(--border-subtle)',
          200: 'var(--border-default)',
          300: 'var(--border-strong)',
          400: 'var(--border-brand)',
          500: 'var(--border-focus)',
        },
        risk: {
          low: {
            bg:     'var(--risk-low-bg)',
            border: 'var(--risk-low-border)',
            text:   'var(--risk-low-text)',
            dot:    'var(--risk-low-dot)',
          },
          medium: {
            bg:     'var(--risk-medium-bg)',
            border: 'var(--risk-medium-border)',
            text:   'var(--risk-medium-text)',
            dot:    'var(--risk-medium-dot)',
          },
          high: {
            bg:     'var(--risk-high-bg)',
            border: 'var(--risk-high-border)',
            text:   'var(--risk-high-text)',
            dot:    'var(--risk-high-dot)',
          },
          critical: {
            bg:     'var(--risk-critical-bg)',
            border: 'var(--risk-critical-border)',
            text:   'var(--risk-critical-text)',
            dot:    'var(--risk-critical-dot)',
          },
        },
        status: {
          allow:   'var(--risk-low-dot)',
          review:  'var(--risk-medium-dot)',
          block:   'var(--risk-high-dot)',
          neutral: 'var(--text-tertiary)',
          success: {
            bg:     'var(--status-success-bg)',
            text:   'var(--status-success-text)',
            border: 'var(--status-success-border)',
          },
          warning: {
            bg:     'var(--status-warning-bg)',
            text:   'var(--status-warning-text)',
            border: 'var(--status-warning-border)',
          },
          error: {
            bg:     'var(--status-error-bg)',
            text:   'var(--status-error-text)',
            border: 'var(--status-error-border)',
          },
          info: {
            bg:     'var(--status-info-bg)',
            text:   'var(--status-info-text)',
            border: 'var(--status-info-border)',
          },
        },
        // brand aliases
        cyan: {
          50:  'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: '#0E7490',
          900: '#155E75',
        }
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
      },
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        'full': 'var(--radius-full)',
        'DEFAULT': 'var(--radius-md)',
      },
      transitionTimingFunction: {
        'ease-out-expo': 'var(--ease-out-expo)',
        'ease-spring':   'var(--ease-spring)',
      },
      transitionDuration: {
        'instant': 'var(--duration-instant)',
        'fast':    'var(--duration-fast)',
        'normal':  'var(--duration-normal)',
        'slow':    'var(--duration-slow)',
        'enter':   'var(--duration-enter)',
      },
      spacing: {
        'sp-1':  'var(--space-1)',
        'sp-2':  'var(--space-2)',
        'sp-3':  'var(--space-3)',
        'sp-4':  'var(--space-4)',
        'sp-5':  'var(--space-5)',
        'sp-6':  'var(--space-6)',
        'sp-8':  'var(--space-8)',
        'sp-10': 'var(--space-10)',
        'sp-12': 'var(--space-12)',
        'sp-16': 'var(--space-16)',
        'sp-20': 'var(--space-20)',
        'sp-24': 'var(--space-24)',
        'sp-32': 'var(--space-32)',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
