/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"Noto Sans"', 'Helvetica', 'Arial', 'sans-serif', '"Apple Color Emoji"', '"Segoe UI Emoji"'],
        display: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"Noto Sans"', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', '"SF Mono"', 'Menlo', 'Consolas', '"Liberation Mono"', 'monospace'],
      },
      colors: {
        surface: {
          '000': 'var(--surface-000)',
          '100': 'var(--surface-100)',
          '200': 'var(--surface-200)',
          '300': 'var(--surface-300)',
          '400': 'var(--surface-400)',
          '500': 'var(--surface-500)',
          '600': 'var(--surface-600)',
          '700': 'var(--surface-700)',
        },
        cyan: {
          50:  'var(--cyan-50)',
          100: 'var(--cyan-100)',
          200: 'var(--cyan-200)',
          300: 'var(--cyan-300)',
          400: 'var(--cyan-400)',
          500: 'var(--cyan-500)',
          600: 'var(--cyan-600)',
          700: 'var(--cyan-700)',
          800: 'var(--cyan-800)',
          900: 'var(--cyan-900)',
        },
        amber: {
          400: 'var(--amber-400)',
          500: 'var(--amber-500)',
          600: 'var(--amber-600)',
        },
        status: {
          allow:   'var(--status-allow)',
          review:  'var(--status-review)',
          block:   'var(--status-block)',
          neutral: 'var(--status-neutral)',
        },
        text: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary:  'var(--text-tertiary)',
          accent:    'var(--text-accent)',
          inverse:   'var(--text-inverse)',
        },
        border: {
          100: 'var(--border-100)',
          200: 'var(--border-200)',
          300: 'var(--border-300)',
          400: 'var(--border-400)',
          500: 'var(--border-500)',
        }
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        'glow-cyan': 'var(--glow-cyan)',
      },
      transitionTimingFunction: {
        'out-expo': 'var(--ease-out-expo)',
        'in-expo':  'var(--ease-in-expo)',
        'spring':   'var(--ease-spring)',
        'smooth':   'var(--ease-smooth)',
      },
      transitionDuration: {
        'fast':   'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow':   'var(--duration-slow)',
        'enter':  'var(--duration-enter)',
      },
      spacing: {
        'sp-1':  'var(--sp-1)',
        'sp-2':  'var(--sp-2)',
        'sp-3':  'var(--sp-3)',
        'sp-4':  'var(--sp-4)',
        'sp-5':  'var(--sp-5)',
        'sp-6':  'var(--sp-6)',
        'sp-8':  'var(--sp-8)',
        'sp-10': 'var(--sp-10)',
        'sp-12': 'var(--sp-12)',
        'sp-16': 'var(--sp-16)',
        'sp-20': 'var(--sp-20)',
        'sp-24': 'var(--sp-24)',
        'sp-32': 'var(--sp-32)',
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'DEFAULT': '8px',
        'md': '10px',
        'lg': '12px',
        'xl': '14px',
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}
