import uuid
import asyncio
from typing import Any
from datetime import datetime
from sqlalchemy import select, update, func, desc
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.alert import Alert
from app.models.alert_activity import AlertActivity
from app.models.transaction import Transaction
from app.db.session import AsyncSessionLocal

_background_tasks = set()

class AlertService:
    @staticmethod
    async def create_alert(
        org_id: uuid.UUID,
        transaction_id: uuid.UUID,
        severity: str,
        title: str,
        description: str,
        db: AsyncSession = None
    ) -> Alert:
        if db is None:
            async with AsyncSessionLocal() as session:
                return await AlertService._create_alert_logic(session, org_id, transaction_id, severity, title, description)
        else:
            return await AlertService._create_alert_logic(db, org_id, transaction_id, severity, title, description)

    @staticmethod
    async def _create_alert_logic(
        db: AsyncSession,
        org_id: uuid.UUID,
        transaction_id: uuid.UUID,
        severity: str,
        title: str,
        description: str
    ) -> Alert:
        alert = Alert(
            org_id=org_id,
            transaction_id=transaction_id,
            severity=severity,
            title=title,
            description=description,
            status="open"
        )
        db.add(alert)
        await db.flush() # Get the ID
        
        # Log initial activity
        activity = AlertActivity(
            alert_id=alert.id,
            org_id=org_id,
            from_status=None,
            to_status="open",
            note="Alert automatically generated by ML engine"
        )
        db.add(activity)
        await db.commit()
        await db.refresh(alert)
        
        # Notify via WebSocket (Implementation in later step)
        from app.api.v1.websocket import broadcast_alert
        task = asyncio.create_task(broadcast_alert(org_id, alert))
        _background_tasks.add(task)
        task.add_done_callback(_background_tasks.discard)
        
        return alert

    @staticmethod
    async def update_alert_status(
        db: AsyncSession,
        alert_id: uuid.UUID,
        org_id: uuid.UUID,
        new_status: str,
        changed_by: uuid.UUID,
        note: str = None
    ) -> Alert | None:
        result = await db.execute(
            select(Alert).where(Alert.id == alert_id, Alert.org_id == org_id)
        )
        alert = result.scalar_one_or_none()
        if not alert:
            return None
        
        old_status = alert.status
        alert.status = new_status
        
        if new_status in ["resolved", "false_positive"]:
            alert.resolved_by = changed_by
            alert.resolved_at = datetime.utcnow()
        elif new_status == "in_review":
            alert.assigned_to = changed_by
            
        activity = AlertActivity(
            alert_id=alert.id,
            org_id=org_id,
            from_status=old_status,
            to_status=new_status,
            changed_by=changed_by,
            note=note
        )
        db.add(activity)
        await db.commit()
        await db.refresh(alert)
        return alert

    @staticmethod
    async def get_alerts_paginated(
        db: AsyncSession,
        org_id: uuid.UUID,
        status: str = "open",
        severity: str = "all",
        page: int = 1,
        per_page: int = 25
    ) -> dict[str, Any]:
        from sqlalchemy.orm import joinedload
        query = select(Alert).options(joinedload(Alert.transaction)).where(Alert.org_id == org_id)
        
        if status != "all":
            query = query.where(Alert.status == status)
        if severity != "all":
            query = query.where(Alert.severity == severity)
            
        # Count total
        count_query = select(func.count()).select_from(query.alias())
        total_result = await db.execute(count_query)
        total = total_result.scalar() or 0
        
        # Pagination
        query = query.order_by(
            desc(Alert.severity == "critical"),
            desc(Alert.severity == "high"),
            desc(Alert.created_at)
        ).offset((page - 1) * per_page).limit(per_page)
        
        result = await db.execute(query)
        alerts = result.scalars().all()
        
        # Unread count
        unread_result = await db.execute(
            select(func.count(Alert.id)).where(Alert.org_id == org_id, Alert.status == "open")
        )
        unread_count = unread_result.scalar() or 0
        
        return {
            "alerts": alerts,
            "total": total,
            "page": page,
            "per_page": per_page,
            "unread_count": unread_count
        }

    @staticmethod
    async def get_alert_stats(db: AsyncSession, org_id: uuid.UUID) -> dict[str, Any]:
        result = await db.execute(
            select(
                func.count(Alert.id).filter(Alert.status == "open").label("open"),
                func.count(Alert.id).filter(Alert.status == "in_review").label("in_review"),
                func.count(Alert.id).filter(Alert.severity == "critical").label("critical"),
                func.count(Alert.id).filter(Alert.severity == "high").label("high"),
                func.count(Alert.id).filter(Alert.severity == "medium").label("medium")
            ).where(Alert.org_id == org_id)
        )
        stats = result.mappings().first()
        
        # Simple stats for demonstration
        return {
            **stats,
            "resolved_today": 0,
            "false_positives_today": 0,
            "avg_resolution_time_minutes": 15
        }
