"""create_dispute_tables

Revision ID: 50cebf04055e
Revises: production_blueprint
Create Date: 2026-07-04 06:53:16.315230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50cebf04055e'
down_revision: Union[str, None] = 'production_blueprint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dispute_reference', sa.String(length=255), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('dispute_type', sa.String(length=50), nullable=False),
    sa.Column('dispute_reason', sa.String(length=255), nullable=True),
    sa.Column('dispute_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('outcome_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_evidence_gathered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('response_document_url', sa.Text(), nullable=True),
    sa.Column('ml_risk_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ml_fraud_signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('merchant_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_source', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('is_included_in_response', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('days_before_deadline', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), server_default='system', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Custom indexes
    op.create_index('idx_disputes_org_status', 'disputes', ['org_id', 'status', 'response_deadline'])
    op.create_index(
        'idx_disputes_deadline', 
        'disputes', 
        ['response_deadline'], 
        postgresql_where=sa.text("status IN ('open', 'evidence_gathering')")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_disputes_deadline', table_name='disputes')
    op.drop_index('idx_disputes_org_status', table_name='disputes')
    op.drop_table('dispute_timeline')
    op.drop_table('dispute_reminders')
    op.drop_table('dispute_evidence')
    op.drop_table('disputes')
    # ### end Alembic commands ###
