"""add waitlist table

Revision ID: 8b9073b465dc
Revises: 20250412_02
Create Date: 2026-04-15 15:27:59.326300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9073b465dc'
down_revision: Union[str, None] = '20250412_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=True)
    op.drop_index(op.f('idx_activity_alert'), table_name='alert_activity')
    op.drop_index(op.f('idx_alerts_org_severity'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_org_status'), table_name='alerts')
    op.drop_index(op.f('idx_transactions_created_brin'), table_name='transactions', postgresql_using='brin')
    op.drop_index(op.f('idx_transactions_customer'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_org_created'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_risk_label'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_transactions_risk_label'), 'transactions', ['org_id', 'risk_label'], unique=False)
    op.create_index(op.f('idx_transactions_org_created'), 'transactions', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_transactions_customer'), 'transactions', ['org_id', 'customer_id'], unique=False)
    op.create_index(op.f('idx_transactions_created_brin'), 'transactions', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index(op.f('idx_alerts_org_status'), 'alerts', ['org_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_alerts_org_severity'), 'alerts', ['org_id', 'severity', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_activity_alert'), 'alert_activity', ['alert_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
